version: "3.9"
services:
  db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pmi-gotosw
      - POSTGRES_DB=finomic
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:pmi-gotosw@db:5433/finomic?sslmode=disable